--- 
abstract: Rebase deep data structures
author: Gaal Yahas <gaal@forum2.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Rebless
no_index: 
  directory: 
    - inc
    - t
requires: 
  Scalar::Util: 1.01
version: 0.08
